# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /uio/hume/student-u41/wonhol/pc/work/inf4431/lab4/lab4/task1/task1_project_2/task1_project_2.cache/wt [current_project]
set_property parent.project_path /uio/hume/student-u41/wonhol/pc/work/inf4431/lab4/lab4/task1/task1_project_2/task1_project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /uio/hume/student-u41/wonhol/pc/work/inf4431/lab4/lab4/task1/task1_project_2/task1_project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /uio/hume/student-u41/wonhol/pc/work/inf4431/lab4/lab4/task1/compute_pipelined_ent.vhd
  /uio/hume/student-u41/wonhol/pc/work/inf4431/lab4/lab4/task1/compute_pipelined_rtl.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top compute_pipelined -part xc7z020clg484-1


write_checkpoint -force -noxdef compute_pipelined.dcp

catch { report_utilization -file compute_pipelined_utilization_synth.rpt -pb compute_pipelined_utilization_synth.pb }
