# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir M:/pc/work/inf4431/lab3/src/viv_oppg6/viv_oppg6.cache/wt [current_project]
set_property parent.project_path M:/pc/work/inf4431/lab3/src/viv_oppg6/viv_oppg6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo m:/pc/work/inf4431/lab3/src/viv_oppg6/viv_oppg6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  M:/pc/work/inf4431/lab3/src/pos_meas_ent.vhd
  M:/pc/work/inf4431/lab3/src/clkdiv_ent.vhd
  M:/pc/work/inf4431/lab3/src/p_ctrl_ent.vhd
  M:/pc/work/inf4431/lab3/src/rstsynch_ent.vhd
  M:/pc/work/inf4431/lab3/src/subprog_pck.vhd
  M:/pc/work/inf4431/lab3/src/pos_meas_rtl.vhd
  M:/pc/work/inf4431/lab3/src/p_ctrl_rtl.vhd
  M:/pc/work/inf4431/lab3/src/pos_ctrl_ent.vhd
  M:/pc/work/inf4431/lab3/src/decoder.vhd
  M:/pc/work/inf4431/lab3/src/cru_ent.vhd
  M:/pc/work/inf4431/lab3/src/clkdiv_rtl.vhd
  M:/pc/work/inf4431/lab3/src/timer.vhd
  M:/pc/work/inf4431/lab3/src/rstsynch_rtl.vhd
  M:/pc/work/inf4431/lab3/src/subprog_bdy.vhd
  M:/pc/work/inf4431/lab3/src/seg7ctrl_ent.vhd
  M:/pc/work/inf4431/lab3/src/pos_seg7_ctrl_ent.vhd
  M:/pc/work/inf4431/lab3/src/cru_str.vhd
  M:/pc/work/inf4431/lab3/src/pos_ctrl_rtl.vhd
  M:/pc/work/inf4431/lab3/src/seg7ctrl_rtl.vhd
  M:/pc/work/inf4431/lab3/src/pos_seg7_ctrl_str.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc M:/pc/work/inf4431/lab3/src/constraints.xdc
set_property used_in_implementation false [get_files M:/pc/work/inf4431/lab3/src/constraints.xdc]


synth_design -top pos_seg7_ctrl -part xc7z020clg484-1


write_checkpoint -force -noxdef pos_seg7_ctrl.dcp

catch { report_utilization -file pos_seg7_ctrl_utilization_synth.rpt -pb pos_seg7_ctrl_utilization_synth.pb }
