# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir M:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.cache/wt [current_project]
set_property parent.project_path M:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo m:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet m:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.srcs/sources_1/ip/ila_0/ila_0.dcp
set_property used_in_implementation false [get_files m:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.srcs/sources_1/ip/ila_0/ila_0.dcp]
read_vhdl -library xil_defaultlib {
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/subprog_pck.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/rstsynch_ent.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/p_ctrl_ent.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/pos_meas_ent.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/clkdiv_ent.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/timer.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/subprog_bdy.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/seg7ctrl_ent.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/rstsynch_rtl.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/p_ctrl_rtl.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/pos_meas_rtl.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/pos_ctrl_ent.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/lab4_pck.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/decoder.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/cru_ent.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/clkdiv_rtl.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/seg7ctrl_rtl.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/pos_seg7_ctrl_ent.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/pos_ctrl_rtl.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/lab4reg_ent.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/cru_str.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/axi4pifb_ent.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/pos_seg7_ctrl_str.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/lab4_top_ent.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/lab4reg_rtl.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/axi4pifb_rtl.vhd
  M:/pc/work/inf4431/lab4/lab4/task2/src/lab4_toplevel/lab4_top_str.vhd
}
add_files M:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all m:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all m:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all m:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all m:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all m:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all M:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files M:/pc/work/inf4431/lab4/lab4/task2/pr/lab4.srcs/sources_1/bd/design_1/design_1.bd]

read_ip -quiet M:/pc/work/inf4431/lab4/lab4/task2/pr/ram_lab4/ram_lab4.xci
set_property used_in_implementation false [get_files -all m:/pc/work/inf4431/lab4/lab4/task2/pr/ram_lab4/ram_lab4_ooc.xdc]
set_property is_locked true [get_files M:/pc/work/inf4431/lab4/lab4/task2/pr/ram_lab4/ram_lab4.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc M:/pc/work/inf4431/lab4/lab4/task2/constraints/constraints_lab4.xdc
set_property used_in_implementation false [get_files M:/pc/work/inf4431/lab4/lab4/task2/constraints/constraints_lab4.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top lab4_top -part xc7z020clg484-1


write_checkpoint -force -noxdef lab4_top.dcp

catch { report_utilization -file lab4_top_utilization_synth.rpt -pb lab4_top_utilization_synth.pb }
