# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir M:/pc/work/inf4431/lab2/vivado_prj/oppg1/oppg1.cache/wt [current_project]
set_property parent.project_path M:/pc/work/inf4431/lab2/vivado_prj/oppg1/oppg1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo m:/pc/work/inf4431/lab2/vivado_prj/oppg1/oppg1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib M:/pc/work/inf4431/lab2/src/pargen.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top pargen -part xc7z020clg484-1


write_checkpoint -force -noxdef pargen.dcp

catch { report_utilization -file pargen_utilization_synth.rpt -pb pargen_utilization_synth.pb }
