set_property IOSTANDARD LVCMOS33 [get_ports {INP[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {INP[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTP[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTP[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTP[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTP[0]}]
set_property PACKAGE_PIN G22 [get_ports {INP[1]}]
set_property PACKAGE_PIN F22 [get_ports {INP[0]}]
set_property PACKAGE_PIN U21 [get_ports {OUTP[3]}]
set_property PACKAGE_PIN U22 [get_ports {OUTP[2]}]
set_property PACKAGE_PIN T21 [get_ports {OUTP[1]}]
set_property PACKAGE_PIN T22 [get_ports {OUTP[0]}]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK]
